### ISSUE TITLE
current file as environmental variable

### ISSUE THREAD

**Issue by kbro237** [CDSoft/panda#1]
Thanks for this project! I'm currently evaluating whether I can replace `pp` with `panda` or if I still need a preprocessor like `upp`.

Is there a way to access the name of the current file from `panda`? For example, with `pp` I used the macro `!exec(date -r !file "+%Y-%m-%d")` to set the metadata date to the date of the file's last modification.

**Comment by CDSoft** [comment]
Hi,

Panda does not know the current file since it works on the AST, not on the file.
A workaround would be to set an environment variable before calling panda.

On the other side, pandoc provides a Lua table `PANDOC_STATE` which contains information about the input files. I can check if this table can be made available to panda.

**Comment by CDSoft** [comment]
I'm testing something in the branch `input_and_output_files`:
- we can execute scripts with `icmd` instead of `cmd` to include the result of the command as a markdown text instead of in a code block
- there are two variables: `input_file` and `output_file`

Thus we can write:

```
% test mdate
% someone
% `date -r {{input_file}} "+%Y-%m-%d"`{icmd=sh}
```

**Comment by CDSoft** [comment]
I've merged the branch `input_and_output_files`.
I've also added similar variables to upp.
